CREATE TABLE IF NOT EXISTS trade_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP NOT NULL,
    app_user_id BIGINT,
    trigger_request_id BIGINT,
    trade_id BIGINT,
    strategy_id VARCHAR(120),
    source VARCHAR(160),
    symbol VARCHAR(255),
    event_type VARCHAR(80) NOT NULL,
    outcome VARCHAR(40),
    reason VARCHAR(1200),
    option_type VARCHAR(255),
    expiry VARCHAR(255),
    strike_price DOUBLE PRECISION,
    spot_price DOUBLE PRECISION,
    option_ltp DOUBLE PRECISION,
    best_bid DOUBLE PRECISION,
    best_ask DOUBLE PRECISION,
    details TEXT
);

CREATE INDEX IF NOT EXISTS idx_trade_audit_user_time
    ON trade_audit_events (app_user_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_trade_audit_request
    ON trade_audit_events (trigger_request_id);
CREATE INDEX IF NOT EXISTS idx_trade_audit_trade
    ON trade_audit_events (trade_id);
