CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(1024),
    customer_id BIGINT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS broker_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broker_name VARCHAR(255) NOT NULL,
    customer_id BIGINT,
    app_user_id BIGINT,
    api_key VARCHAR(1024),
    broker_username VARCHAR(512),
    broker_password VARCHAR(1024),
    client_code VARCHAR(256),
    totp_secret VARCHAR(1024),
    secret_key VARCHAR(1024),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    trading_enabled BOOLEAN,
    default_for_orders BOOLEAN
);

CREATE INDEX IF NOT EXISTS idx_broker_credentials_user
    ON broker_credentials (app_user_id);
CREATE INDEX IF NOT EXISTS idx_broker_credentials_customer
    ON broker_credentials (broker_name, customer_id);
