package org.com.sharekhan.backtest;

import org.com.sharekhan.entity.*;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import org.springframework.jdbc.core.namedparam.*;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.support.TransactionTemplate;
import java.util.*;

@Repository
@ConditionalOnProperty(prefix="app.backtest.postgres",name="enabled",havingValue="true")
public class PostgresBacktestReplayStore implements BacktestReplayStore {
 private final NamedParameterJdbcTemplate jdbc; private final TransactionTemplate tx;
 private static final BeanPropertyRowMapper<BacktestReplayResultEntity> MAPPER=new BeanPropertyRowMapper<>(BacktestReplayResultEntity.class);
 public PostgresBacktestReplayStore(@Qualifier("auditPostgresJdbcTemplate") NamedParameterJdbcTemplate j,@Qualifier("auditPostgresTransactionManager") org.springframework.transaction.PlatformTransactionManager tm){jdbc=j;tx=new TransactionTemplate(tm);}
 private static final String COLS="trade_setup_id,app_user_id,broker_credentials_id,broker_name,simulator,trade_date,source,symbol,scrip_code,option_type,strike_price,expiry,candle_interval,trigger_price_policy,square_off_time,intraday_only,status,message,backtest_entry_at,backtest_exit_at,backtest_exit_price,backtest_exit_reason,backtest_pnl,backtest_exit_count,actual_entry_at,actual_exit_at,actual_exit_price,actual_exit_reason,actual_pnl,run_at,created_at,updated_at";
 private static final String PARAMS=":tradeSetupId,:appUserId,:brokerCredentialsId,:brokerName,:simulator,:tradeDate,:source,:symbol,:scripCode,:optionType,:strikePrice,:expiry,:interval,:triggerPricePolicy,:squareOffTime,:intradayOnly,:status,:message,:backtestEntryAt,:backtestExitAt,:backtestExitPrice,:backtestExitReason,:backtestPnl,:backtestExitCount,:actualEntryAt,:actualExitAt,:actualExitPrice,:actualExitReason,:actualPnl,:runAt,:createdAt,:updatedAt";
 private static final String SELECT="SELECT id,trade_setup_id,app_user_id,broker_credentials_id,broker_name,simulator,trade_date,source,symbol,scrip_code,option_type,strike_price,expiry,candle_interval AS interval,trigger_price_policy,square_off_time,intraday_only,status,message,backtest_entry_at,backtest_exit_at,backtest_exit_price,backtest_exit_reason,backtest_pnl,backtest_exit_count,actual_entry_at,actual_exit_at,actual_exit_price,actual_exit_reason,actual_pnl,run_at,created_at,updated_at FROM backtest_replay_results";
 public Optional<BacktestReplayResultEntity> findResult(Long id,String interval,String policy,String time){List<BacktestReplayResultEntity> x=jdbc.query(SELECT+" WHERE trade_setup_id=:id AND candle_interval=:interval AND trigger_price_policy=:policy AND square_off_time=:time",new MapSqlParameterSource().addValue("id",id).addValue("interval",interval).addValue("policy",policy).addValue("time",time),MAPPER);return x.stream().findFirst();}
 public BacktestReplayResultEntity saveResult(BacktestReplayResultEntity r){String sql="INSERT INTO backtest_replay_results ("+COLS+") VALUES ("+PARAMS+") ON CONFLICT (trade_setup_id,candle_interval,trigger_price_policy,square_off_time) DO UPDATE SET app_user_id=EXCLUDED.app_user_id,broker_credentials_id=EXCLUDED.broker_credentials_id,status=EXCLUDED.status,message=EXCLUDED.message,backtest_entry_at=EXCLUDED.backtest_entry_at,backtest_exit_at=EXCLUDED.backtest_exit_at,backtest_exit_price=EXCLUDED.backtest_exit_price,backtest_exit_reason=EXCLUDED.backtest_exit_reason,backtest_pnl=EXCLUDED.backtest_pnl,backtest_exit_count=EXCLUDED.backtest_exit_count,actual_entry_at=EXCLUDED.actual_entry_at,actual_exit_at=EXCLUDED.actual_exit_at,actual_exit_price=EXCLUDED.actual_exit_price,actual_exit_reason=EXCLUDED.actual_exit_reason,actual_pnl=EXCLUDED.actual_pnl,run_at=EXCLUDED.run_at,updated_at=EXCLUDED.updated_at RETURNING id"; Long id=jdbc.queryForObject(sql,new BeanPropertySqlParameterSource(r),Long.class);r.setId(id);return r;}
 public void replaceEvents(Long id,List<BacktestReplayEventEntity> e){tx.executeWithoutResult(s->{jdbc.update("DELETE FROM backtest_replay_events WHERE result_id=:id",new MapSqlParameterSource("id",id));if(!e.isEmpty())jdbc.batchUpdate("INSERT INTO backtest_replay_events (result_id,trade_setup_id,event_index,event_at,event_type,reason,candle_interval,trigger_price_policy,square_off_time,price_source,reference_price,option_price,stop_loss,target,quantity,lots,pnl,run_at) VALUES (:resultId,:tradeSetupId,:eventIndex,:eventAt,:eventType,:reason,:interval,:triggerPricePolicy,:squareOffTime,:priceSource,:referencePrice,:optionPrice,:stopLoss,:target,:quantity,:lots,:pnl,:runAt)",e.stream().map(BeanPropertySqlParameterSource::new).toArray(SqlParameterSource[]::new));});}
 void copyResults(List<BacktestReplayResultEntity> rows){if(rows.isEmpty())return;jdbc.batchUpdate("INSERT INTO backtest_replay_results (id,"+COLS+") OVERRIDING SYSTEM VALUE VALUES (:id,"+PARAMS+") ON CONFLICT (id) DO NOTHING",rows.stream().map(BeanPropertySqlParameterSource::new).toArray(SqlParameterSource[]::new));}
 void copyEvents(List<BacktestReplayEventEntity> rows){if(rows.isEmpty())return;jdbc.batchUpdate("INSERT INTO backtest_replay_events (id,result_id,trade_setup_id,event_index,event_at,event_type,reason,candle_interval,trigger_price_policy,square_off_time,price_source,reference_price,option_price,stop_loss,target,quantity,lots,pnl,run_at) OVERRIDING SYSTEM VALUE VALUES (:id,:resultId,:tradeSetupId,:eventIndex,:eventAt,:eventType,:reason,:interval,:triggerPricePolicy,:squareOffTime,:priceSource,:referencePrice,:optionPrice,:stopLoss,:target,:quantity,:lots,:pnl,:runAt) ON CONFLICT (id) DO NOTHING",rows.stream().map(BeanPropertySqlParameterSource::new).toArray(SqlParameterSource[]::new));}
 long countResults(){Long x=jdbc.getJdbcTemplate().queryForObject("SELECT COUNT(*) FROM backtest_replay_results",Long.class);return x==null?0:x;} long countEvents(){Long x=jdbc.getJdbcTemplate().queryForObject("SELECT COUNT(*) FROM backtest_replay_events",Long.class);return x==null?0:x;}
 void syncSequences(){jdbc.getJdbcTemplate().execute("SELECT setval(pg_get_serial_sequence('backtest_replay_results','id'),COALESCE((SELECT MAX(id) FROM backtest_replay_results),1),true)");jdbc.getJdbcTemplate().execute("SELECT setval(pg_get_serial_sequence('backtest_replay_events','id'),COALESCE((SELECT MAX(id) FROM backtest_replay_events),1),true)");}
}
